### ISSUE TITLE
installation problem appinventor-tfjs

### ISSUE THREAD

**Issue by seghier** [mit-cml/tfjs-extension-tool#3]
Hello, how i can solve the problem ?
```
python -m appinventor.tfjs posenet edu.mit.appinventor.ai.posenet.PosenetExtension
Traceback (most recent call last):
  File "C:\Python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python37\lib\site-packages\appinventor\tfjs\__main__.py", line 265, in <module>
    main()
  File "C:\Python37\lib\site-packages\appinventor\tfjs\__main__.py", line 219, in main
    shutil.rmtree(class_name)
  File "C:\Python37\lib\shutil.py", line 516, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "C:\Python37\lib\shutil.py", line 395, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "C:\Python37\lib\shutil.py", line 395, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "C:\Python37\lib\shutil.py", line 395, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "C:\Python37\lib\shutil.py", line 400, in _rmtree_unsafe
    onerror(os.unlink, fullname, sys.exc_info())
  File "C:\Python37\lib\shutil.py", line 398, in _rmtree_unsafe
    os.unlink(fullname)
PermissionError: [WinError 5] Access is denied: 'PosenetExtension\\.git\\objects\\04\\0adb3ddfa2db86a3e329ebb44fa10c7f78b5e5'
```

**Comment by seghier** [comment]
I try again but other errors

PS C:\Users\user> python -m appinventor.tfjs facemesh com.example.tfjs.face.FaceMeshExtension
Cloning repo from GitHub...
Installing model from npm...
Traceback (most recent call last):
  File "C:\Python37\lib\site-packages\appinventor\tfjs\__main__.py", line 252, in main
    run(d)
  File "C:\Python37\lib\site-packages\appinventor\tfjs\__main__.py", line 236, in run
    for peer in install(model_package):
  File "C:\Python37\lib\site-packages\appinventor\tfjs\__main__.py", line 60, in install
    stderr=subprocess.STDOUT)
  File "C:\Python37\lib\subprocess.py", line 472, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Python37\lib\subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "C:\Python37\lib\subprocess.py", line 1178, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python37\lib\site-packages\appinventor\tfjs\__main__.py", line 263, in <module>
    main()
  File "C:\Python37\lib\site-packages\appinventor\tfjs\__main__.py", line 252, in main
    run(d)
  File "C:\Python37\lib\tempfile.py", line 805, in __exit__
    self.cleanup()
  File "C:\Python37\lib\tempfile.py", line 809, in cleanup
    _shutil.rmtree(self.name)
  File "C:\Python37\lib\shutil.py", line 516, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "C:\Python37\lib\shutil.py", line 404, in _rmtree_unsafe
    onerror(os.rmdir, path, sys.exc_info())
  File "C:\Python37\lib\shutil.py", line 402, in _rmtree_unsafe
    os.rmdir(path)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\user\\FaceMeshExtension\\tmp0n0xtf_5'

**Comment by seghier** [comment]
I use Windows Subsystem for Linux and everything work fine with ubuntu
the extensions created automatically in a folder called out but ther is a problem with speech-commands, can't create extension

**Comment by rulo-codes** [comment]
I am also having PermissionError: Access Denied for Posenet extension too. Where you able to fix this? How did you do it?
